//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NGOassignment.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Configuration;
    using System.Data;
    using System.Data.SqlClient;
    using System.Web.Mvc;

    public partial class UserNGO
    {
        public enum Roles
        {
           Admin,
           User
        }
        [Required(ErrorMessage = "Please enter your User ID.")]
        public string UserID { get; set; }
        public string First_Name { get; set; }
        public string Last_Name { get; set; }
        public string Email { get; set; }
        [DataType(DataType.Password)]
        [Required(ErrorMessage = "Please enter your Password.")]
        public string Password { get; set; }



        public SelectList DropDownList { get; set; }

        public string Role { get; set; }
        public String LoginProcess(String strUsername, String strPassword)
        {
            String message = "";
            //my connection string
            SqlConnection con = new SqlConnection(ConfigurationManager.ConnectionStrings["conStr"].ConnectionString);
            SqlCommand cmd = new SqlCommand("Select * from UserNGO where UserID=@Username", con);
            cmd.Parameters.AddWithValue("@Username", strUsername);
            try
            {
                con.Open();
                SqlDataReader reader = cmd.ExecuteReader();
                if (reader.Read())
                {
                    Boolean login = (strPassword.Equals(reader["Password"].ToString(), StringComparison.InvariantCulture)) ? true : false;
                    string role = "Admin";
                    string rolecom = reader["Role"].ToString();
                    Boolean rolep = string.Equals(rolecom, role);
                    if (login)
                    {
                        if (rolep)
                        {
                            message = "1";
                            UserID = reader["UserID"].ToString();
                        }
                        else
                            message = "2";
                        
                    }
                    else
                        message = "Invalid Password";
                }
                else
                    message = "Invalid Username";

                reader.Close();
                reader.Dispose();
                cmd.Dispose();
                con.Close();
            }
            catch (Exception ex)
            {
                message = ex.Message.ToString() + "Error.";

            }
            return message;
        }
    }
}
